; This file is not used. If you modify it and want the application to use
; your modifications, start with the "-app /path/to/application.ini"
; argument.
[App]
Vendor=Disruptive Innovations SARL
Name=BlueGriffonDev
RemotingName=bluegriffondev
Version=3.2
BuildID=20260309004549
ID=bluegriffon-dev@bluegriffon.com

[Gecko]
MinVersion=55.0a1
MaxVersion=55.0a1

[XRE]

